"""
Discovery task domain model.

Represents a single discovery task generated by the Buyer Engine.
"""

from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class DiscoveryTask:
    """
    Immutable discovery task.

    A discovery task represents a single search query to be executed
    by a future discovery service.
    """

    query: str

    @classmethod
    def create(
        cls,
        *,
        query: str,
    ) -> "DiscoveryTask":
        query = query.strip()

        if not query:
            raise ValueError(
                "Discovery task query cannot be empty."
            )

        return cls(
            query=query,
        )
